server:
  port: 8181


#h2配置
spring:
  jpa:
    show-sql: true #启用SQL语句的日志记录
    hibernate:
      ddl-auto: update #设置ddl模式
  datasource:
    url: jdbc:h2:file:./h2/db/test #配置h2数据库的连接地址只能存在一个连接，如果想多个连接可在后面拼接参数  ;AUTO_SERVER=TRUE
    username: root #配置数据库用户名
    password: 123456 #配置数据库密码
    driverClassName: org.h2.Driver #配置JDBC Driver
    schema: classpath:db/DDL.sql #进行该配置后，每次启动程序，程序都会运行指定文件，对数据库的结构进行操作。
    #    data:  #进行该配置后，每次启动程序，程序都会运行指定文件，对数据库的数据操作。
    platform: h2  #表明使用的数据库平台是h2
  h2: #h2 web console设置
    console:
      settings:
        web-allow-others: true #进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
      path: /h2 #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
      enabled: true #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。